name: Deploy to VPS

on:
  push:
    branches:
      - main  # یا branch اصلی شما

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: 162.254.32.4
          port: 22
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/duelback/duelback
            git pull --rebase
            source venv/bin/activate
            python3 manage.py collectstatic --noinput
            sudo systemctl daemon-reload
            sudo systemctl restart duelback.com.gunicorn
